# .github/workflows/build.yml
name: Build & Release PersistentFakeTabPlayers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Configure Maven settings (Papermc repo)
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <profiles>
              <profile>
                <id>papermc</id>
                <repositories>
                  <repository>
                    <id>papermc</id>
                    <url>https://repo.papermc.io/repository/maven-public/</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>papermc</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Build with Maven
        run: mvn clean package --batch-mode

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: PersistentFakeTabPlayers
          path: target/PersistentFakeTabPlayers-1.0.jar
